ALTIBASE/Documents

Manuals/Altibase_7.1/kor/GeneralReference_2.md, Manuals/Altibase_7.1/kor/GeneralReference_4.md, Manuals/Altibase_7.1/kor/Replication.md
710 DDL Synchronization manual update
=> 710 branch PROJ-2677 DDL Synchronization manual update

Manuals/Altibase_7.1/kor/Sharding.md, Manuals/Altibase_trunk/kor/Sharding.md
TRCLOG_SHARD_DETAIL -> TRCLOG_DETAIL_SHARD
=> make a correct word

Manuals/Altibase_7.1/kor/Sharding.md, Manuals/Altibase_trunk/kor/Sharding.md
BUG-47094 reset_shard_resident_node 가 샤딩 매뉴얼에 없습니다.
=> BUG-47094 reset_shard_resident_node 가 샤딩 매뉴얼에 없습니다.

Manuals/Altibase_7.1/kor/Sharding.md, Manuals/Altibase_trunk/kor/Sharding.md
=> Spelling correction 

Manuals/Altibase_7.1/kor/JDBC.md, Manuals/Altibase_trunk/kor/JDBC.md
BUG-47639 반영에 따른 메뉴얼 수정입니다.
CDR에서 결정되었듯이 trunk와 710의 기본 설정값이 틀리기 때문에 메뉴얼 상에도 약간의 차이가 있습니다.
=> BUG-47639 added new lob_null_select jdbc property in Hibernate section

Manuals/Altibase_trunk/kor/GeneralReference_4.md
다음 태스크를 위한 메뉴얼 추가입니다 ㅎㅎ
---------------------------------------------------------
TASK-7248 | 2020 라이선스 검사방식 변경
---------------------------------------------------------
=> manual for TASK-7248

Manuals/Altibase_trunk/kor/GeneralReference_4.md
fix other markup code that is removed by me.
=> fix my mistake about markup

Manuals/Altibase_7.1/kor/SpatialSQL.md
=> ST_MakePoint, ST_Point 함수 지원

Manuals/Altibase_trunk/kor/SpatialSQL.md
=> ST_MakePoint, ST_Point 함수지원

Manuals/Altibase_7.1/kor/SpatialSQL.md
=> ST_MakeLine 함수 지원

Manuals/Altibase_7.1/kor/SpatialSQL.md, Manuals/Altibase_trunk/kor/SpatialSQL.md
=> BUG-47966 ST_POLYGONFROMTEXT

Manuals/Altibase_7.1/kor/GeneralReference_2.md, Manuals/Altibase_7.1/kor/LogAnalyzer.md, Manuals/Altibase_7.1/kor/Replication.md
BUG-47761 이중화 대상 테이블에 SPLIT/MERGE/DROP PARTITION 수행 관련 매뉴얼 수정
=> BUG-47761 이중화 대상 테이블에 SPLIT/MERGE/DROP PARTITION 수행 관련 매뉴얼 수정

Manuals/Altibase_7.1/kor/SpatialSQL.md, Manuals/Altibase_trunk/kor/SpatialSQL.md
BUB-47985 st_linestringFromWKB
=> BUB-47985 st_linestringFromWKB

Manuals/Altibase_7.1/kor/Utilities.md, Manuals/Altibase_7.1/kor/iLoader.md, Manuals/Altibase_7.1/kor/iSQL.md, Manuals/Altibase_trunk/kor/Utilities.md, Manuals/Altibase_trunk/kor/iLoader.md, Manuals/Altibase_trunk/kor/iSQL.md
=> bug-47652 File permission

Manuals/Altibase_7.1/kor/GeneralReference_3.md, Manuals/Altibase_trunk/kor/GeneralReference_3.md
BUG-48069 SYS_REPL_OLD_COLUMNS_에 MT_SRID COLUMN이 추가 되었습니다.
=> BUG-48069 SYS_REPL_OLD_COLUMNS_에 MT_SRID COLUMN이 추가 되었습니다.

Manuals/Altibase_7.1/kor/SpatialSQL.md, Manuals/Altibase_7.1/kor/Utilities.md, Manuals/Altibase_7.1/kor/iLoader.md, Manuals/Altibase_trunk/kor/SpatialSQL.md, Manuals/Altibase_trunk/kor/Utilities.md, Manuals/Altibase_trunk/kor/iLoader.md
1. 공간 데이터 마이그레이션에 대한 설명을 SpatialSQL.md에 추가
2. aexport와 iLoader 용어 정리 및 빠진 내용 추가
3. iLoader 매뉴얼 잘못된 부분 삭제
=> BUG-48424 공간 데이터 마이그레이션에 대한 설명이 매뉴얼에 추가되어야 합니다

Manuals/Altibase_7.1/kor/GeneralReference_2.md, Manuals/Altibase_7.1/kor/GeneralReference_4.md, Manuals/Altibase_trunk/kor/GeneralReference_2.md, Manuals/Altibase_trunk/kor/GeneralReference_4.md
BUG-45940
V$REPRECEIVER_PARALLEL_APPLY status column 추가
REPLICATION_RECEIVER_APPLIER_YIELD_COUNT 프로퍼티 추가
=> BUG-45940 REPLICATION_RECEIVER_APPLIER_YIELD_COUNT

Manuals/Altibase_7.1/kor/SpatialSQL.md, Manuals/Altibase_trunk/kor/SpatialSQL.md
Remove all remarks about altiShapeLoader upon the request INC-44447 TSN-136062
=> Remove altiShapeLoader (INC-44447 TSN-136062)

Manuals/Altibase_7.1/kor/JDBC.md, Manuals/Altibase_trunk/kor/JDBC.md
JDBC 메뉴얼에 spec4.2 관련 내용을 추가하였습니다.
(처음에 올린 리뷰가 잘못 업로드 되어 다시 올림)
=> BUG-48643 JDBC 메뉴얼에 jdbc 4.2 스펙 관련된 내용 추가

Manuals/Altibase_7.1/kor/GeneralReference_2.md, Manuals/Altibase_7.1/kor/GeneralReference_3.md
BUG-48515 동일한 ip의 접속 개수가 설정된 size를 초과할 경우 session 연결을 차단하는 기능을 추가합니다.
=> BUG-48515 동일한 ip의 접속 개수가 설정된 size를 초과할 경우 session 연결을 차단하는 기능을 추가합니다.

Manuals/Altibase_7.1/kor/Admin_1.md, Manuals/Altibase_7.1/kor/Utilities.md, Manuals/Altibase_trunk/kor/Admin_1.md, Manuals/Altibase_trunk/kor/Utilities.md
희정님의 요청에 따라 syspassword 파일에 대한 설명을 추가했습니다.
리뷰 부탁드립니다.
=> BUG-49142 [ux] 매뉴얼에 syspassword 파일에 대한 설명이 필요합니다. 

Manuals/Altibase_7.1/kor/MigrationCenter.md, Manuals/Altibase_7.2/kor/Migration Center User's Manual.md, Manuals/Altibase_trunk/kor/MigrationCenter.md
Add TLS version issue and work-around
=> BUG-49404 TLS version issue

Manuals/Altibase_7.1/kor/Migration Center User's Manual.md, Manuals/Altibase_7.2/kor/Migration Center User's Manual.md, Manuals/Altibase_trunk/kor/Migration Center User's Manual.md
Migration Center 7.9 매뉴얼 업데이트 리뷰 부탁드립니다.
상세 내용은 TASK-7363에 등록했습니다.
=> Migration Center 7.9 manual update

Manuals/Altibase_7.1/kor/Precompiler User's Manual.md, Manuals/Altibase_7.2/kor/CLI User's Manual.md, Manuals/Altibase_7.2/kor/Precompiler User's Manual.md, Manuals/Altibase_trunk/kor/CLI User's Manual.md, Manuals/Altibase_trunk/kor/Precompiler User's Manual.md
bug-49462 linux ppc7 장비에서 Interface/sample/sampleTest.sql diff 발생합니다.
=> bug-49462 linux ppc7 장비에서 Interface/sample/sampleTest.sql diff 발생합니다.

Manuals/Altibase_7.2/eng/Utilities Manual.md, Manuals/Altibase_7.2/kor/Utilities Manual.md, Manuals/Altibase_trunk/eng/Utilities Manual.md, Manuals/Altibase_trunk/kor/Utilities Manual.md
Java 1.5 -> 8 변경사항을 알려드리기 위해 PR 요청드렸습니다.
=> BUG-49503 altiMon log4j 보안 문제로 2.17.1 버전으로 업그레이드

Manuals/Altibase_7.1/eng/Utilities Manual.md, Manuals/Altibase_7.1/kor/Utilities Manual.md, Manuals/Altibase_7.2/eng/Utilities Manual.md, Manuals/Altibase_7.2/kor/Utilities Manual.md, Manuals/Altibase_trunk/eng/Utilities Manual.md, Manuals/Altibase_trunk/kor/Utilities Manual.md
log4j 보안 이슈로 인한 업데이트 및 이에 따른 JRE 버전 변경 매뉴얼 변경사항입니다.
이전 PR과 유사하게 리뷰보다는 notification 성격입니다.
=> BUG-49501 dataCompJ log4j 2.17.1

Manuals/Altibase_trunk/kor/README.md
=> BUG-xxxx branch for bug

ReleaseNotes/eng/Altibase_dataCompJ_7_2_Release_Notes.md
기존 dataCompJ 7.1 패키지에 있던 pdf 파일을 참조해서, dataCompJ 7.2 릴리즈 노트 draft 만들었습니다. 
리뷰 부탁드립니다. 감사합니다.
=> Review dataCompJ_7_2_Release_Notes draft

How to Use 3rd Party for Altibase/kor/Tableau User's Guide for Altibase.md
INC-46028 요구사항으로 추가된 설정입니다.  서영준 팀장님 요청사항으로 리뷰어 추가합니다.
=> BUG-49572-TIMESTAMP_TO_DATE

Manuals/Altibase_7.1/kor/JDBC User's Manual.md, Manuals/Altibase_7.2/kor/JDBC User's Manual.md, Manuals/Altibase_trunk/kor/JDBC User's Manual.md
BUG-49488 batch_setbytes_use_lob 속성에 대한 내용을 JDBC 메뉴얼에 추가하였습니다.
=> BUG-49488 batch_setbytes_use_lob 내용 추가

Manuals/Altibase_7.1/eng/SQL Reference.md, Manuals/Altibase_7.1/kor/SQL Reference.md, Manuals/Altibase_7.2/eng/SQL Reference.md, Manuals/Altibase_trunk/eng/SQL Reference.md, Manuals/Altibase_trunk/kor/SQL Reference.md
SQL Reference에 누락된 해당 내용 반영합니다.
=> BUG-45922 큐는 칼럼에 제약조건을 정의할 수 없다는 조건을 명시합니다.

Manuals/Altibase_7.1/eng/Replication Manual.md, Manuals/Altibase_7.2/eng/Replication Manual.md, Manuals/Altibase_trunk/eng/Replication Manual.md
Replication Manual 내 오타 수정합니다.
=> BUG-46240 오타 수정합니다

Manuals/Altibase_7.1/eng/General Reference-2.The Data Dictionary.md, Manuals/Altibase_7.2/eng/General Reference-2.The Data Dictionary.md, Manuals/Altibase_trunk/eng/General Reference-2.The Data Dictionary.md
=> BUG-46663 V$ACCESS_LIST의 누락된 컬럼들을 추가합니다

Manuals/Altibase_7.1/eng/General Reference-2.The Data Dictionary.md, Manuals/Altibase_7.1/kor/General Reference-2.The Data Dictionary.md, Manuals/Altibase_7.2/eng/General Reference-2.The Data Dictionary.md, Manuals/Altibase_trunk/eng/General Reference-2.The Data Dictionary.md, Manuals/Altibase_trunk/kor/General_Reference-2.The Data Dictionary.md
V$SESSION의 REPLICATION_MODE 기본값 수정합니다.
=> BUG-45686 V$SESSION의 REPLICATION_MODE 기본값 수정합니다.

Manuals/Altibase_7.1/eng/Performance Tuning Guide.md, Manuals/Altibase_7.2/eng/Performance Tuning Guide.md, Manuals/Altibase_trunk/eng/Performance Tuning Guide.md
Performance Tuning Guide의 INDEX DESC 힌트 내용 추가합니다.
수정하면서 목차가 잘못된 것을 확인하여 목차도 수정합니다.
=> BUG-41450 Performance Tuning Guide의 INDEX DESC 힌트 내용 추가

Manuals/Altibase_7.1/eng/Adapter for Oracle User's Manual.md, Manuals/Altibase_7.2/eng/Adapter for Oracle User's Manual.md, Manuals/Altibase_trunk/eng/Adapter for Oracle User's Manual.md
희정님께서 남겨주신 리뷰와 브랜치 이름 수정하여 풀 리퀘스트 재생성합니다.
브랜치 이름을 변경 시에도 풀 리퀘스트를 다시 생성해야 하는 것 같습니다.
=> BUG-46176 Adapter for Oracle User's Manual 내용 수정

Manuals/Altibase_7.1/eng/Administrator's Manual.md, Manuals/Altibase_7.2/eng/Administrator's Manual.md, Manuals/Altibase_trunk/eng/Administrator’s Manual.md
BUG-41105 JOB에 관한 내용을 보충합니다.
목차에서 Job 클릭 시 다른 부분으로 연결되어 수정합니다.
=> BUG-41105 JOB에 관한 내용을 보충합니다.

Manuals/Altibase_7.1/eng/SQL Reference.md, Manuals/Altibase_7.2/eng/SQL Reference.md, Manuals/Altibase_trunk/eng/SQL Reference.md
BUG-43991 SQL Reference에서 ADD_MONTH에 대한 설명 보충합니다.
=> BUG-43991 SQL Reference에서 ADD_MONTH에 대한 설명 보충합니다.

Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
E. 부록 부분 가독성 좋게 변경했습니다. 
- 점목록 사용 제거
- SQL 문 코드 펜스 사용
- Altibase x.x.x.0.0 -> Altibase x.x.x
- 버전 범위: Altibase 6.5.1.0.0 이전 -> 이 규칙은 Altibase x.x.x ~ 버전에 적용된다.
=> Bug 49898 modify e. appendix

Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
Reverts ALTIBASE/Documents#278
=> Revert "Bug 49898 modify e. appendix"

Technical Documents/kor/Supported Platforms.md
=> Update Supported Platforms.md

Manuals/Altibase_7.1/kor/SQL Reference.md, Manuals/Altibase_trunk/kor/Error Message Reference.md
=> Bug 49952 regexp mode 관련 설명 개선

Manuals/Altibase_7.1/kor/Error Message Reference.md, Manuals/Altibase_7.1/kor/General Reference-2.The Data Dictionary.md, Manuals/Altibase_trunk/kor/Error Message Reference.md, Manuals/Altibase_trunk/kor/General_Reference-2.The Data Dictionary.md
- Update V$QUEUE_DELETE_OFF's description
- Add 0x314AA error messages
=> Bug 49063 queue table

Manuals/Altibase_7.1/kor/Utilities Manual.md, Manuals/Altibase_trunk/kor/Utilities Manual.md
=> Update Utilities Manual.md

Manuals/Altibase_trunk/kor/SQL Reference.md
BUG-49953 Grouping sets with window function
=> BUG-50085 GROUPING SETS with window function

Manuals/Altibase_trunk/kor/SQL Reference.md
Reverts ALTIBASE/Documents#319
=> Revert "BUG-50085 GROUPING SETS with window function"

Manuals/Tools/Altibase_release/eng/Migration Center User's Manual.md
bug-50190 fix migration center -postgreSQL to altibase
=> bug-50190 fix migration center -postgreSQL to altibase

ReleaseNotes/eng/Altibase_Migration_Center_7_13_Release_Notes.md, ReleaseNotes/kor/Altibase_Migration_Center_7_13_Release_Notes.md
Migration Center 7.13 릴리즈 노트 한글/영문 draft 작성했습니다. 리뷰 부탁드립니다.
=> Migration Center 7.13 릴리즈 노트

Manuals/Altibase_trunk/kor/Administrator's Manual.md, Manuals/Altibase_trunk/kor/Altibase SSL TLS User's Guide.md, Manuals/Altibase_trunk/kor/General_Reference-1.Data Types & Altibase Properties.md
=> TASK-7513 draft 작성 및 리뷰요청

Manuals/Altibase_7.1/kor/SQL Reference.md, Manuals/Altibase_trunk/kor/SQL Reference.md
=> BUG-49803, BUG-49810 수정사항

Manuals/Altibase_7.1/eng/Utilities Manual.md, Manuals/Altibase_trunk/eng/Utilities Manual.md
=> 7.1, trunk 매뉴얼에 반영, 대소문자 수정

Manuals/Altibase_trunk/kor/General_Reference-2.The Data Dictionary.md, Manuals/Altibase_trunk/kor/Replication Manual.md
'[BUG-49575] "BUG-42613 propagation 신규 기능 추가" 관련 매뉴얼 개선 ' 관련하여 이중화 롤 이라는 항목을 추가했습니다. 
general reference도 함께 수정했습니다. 이중화 매뉴얼의 목차는 어떻게 하는지 몰라서 갱신하지 못했습니다. 
확인 부탁드립니다.
=> replication role fix

Manuals/Altibase_7.1/eng/JDBC User's Manual.md, Manuals/Altibase_7.1/kor/JDBC User's Manual.md, Manuals/Altibase_7.3/eng/JDBC User's Manual.md, Manuals/Altibase_7.3/kor/JDBC User's Manual.md, Manuals/Altibase_trunk/eng/JDBC User's Manual.md, Manuals/Altibase_trunk/kor/JDBC User's Manual.md
=> PING쿼리 허용되는 패턴, 허용되지 않는 패턴 수정

Manuals/Tools/Altibase_release/eng/Replication Manager User's Manual.md, Manuals/Tools/Altibase_release/kor/Replication Manager User's Manual.md, Manuals/Tools/Altibase_trunk/eng/Replication Manager User's Manual.md, Manuals/Tools/Altibase_trunk/kor/Replication Manager User's Manual.md, ReleaseNotes/eng/Altibase_Replication_Manager_1_4_Release_Notes.md, ReleaseNotes/kor/Altibase_Replication_Manager_1_4_Release_Notes.md
Replication Manager와 Altibase 7.3 JDBC 파일 호환성 이슈를 해결하기 위한 "BUG-50573 Replication Manager에 패키징된 JRE를 6 -> 8로 업데이트 해야 합니다"가 적용된 1.4 릴리즈 노트를 새로 작성했습니다.
1.3 릴리즈 노트와 비교하시면 좀더 손쉽게 리뷰 가능합니다.
바쁘시겠지만, 빠른 리뷰 부탁드립니다.
=> Add 1.4 release notes

Manuals/Altibase_trunk/eng/Utilities Manual.md
BUG-50596 AKU_REPLICATION_RESET_AT_END 영문 매뉴얼 추가, 목차 수정 반영
=> BUG-50596 AKU_REPLICATION_RESET_AT_END 영문 매뉴얼 추가, 목차 수정 반영

Manuals/Altibase_7.1/kor/Replication Manual.md, Manuals/Altibase_7.1/kor/Utilities Manual.md, Manuals/Altibase_7.3/kor/Replication Manual.md, Manuals/Altibase_7.3/kor/Utilities Manual.md, Manuals/Altibase_trunk/kor/Replication Manual.md, Manuals/Altibase_trunk/kor/Utilities Manual.md
=> BUG-50593 반영

Manuals/Altibase_7.3/kor/Installation Guide.md, Manuals/Altibase_trunk/kor/Installation Guide.md, ReleaseNotes/kor/Altibase_7_3_0_0_1_Release_Notes.md, Technical Documents/kor/Supported Platforms.md
BUG-50657 fix
Windows client 지원으로 문서 수정했습니다.
=> BUG-50657 fix

Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
=> Update Migration Center User's Manual.md

Technical Documents/kor/Supported Platforms.md
=> BUG-50760 rocky 8.6 updated

Manuals/Tools/Altibase_trunk/kor/Altibase 3rd Party Connector Guide.md
=> Update Altibase 3rd Party Connector Guide.md

Manuals/Altibase_7.1/kor/Replication Manual.md, Manuals/Altibase_7.3/kor/Replication Manual.md, Manuals/Altibase_trunk/kor/Replication Manual.md
=> Update Replication Manual

Manuals/Altibase_7.3/eng/Stored Procedures Manual.md, Manuals/Altibase_trunk/eng/Stored Procedures Manual.md
=> Stored Procedures Manual - Fetch across rollback

Manuals/Altibase_7.3/eng/iSQL User's Manual.md, Manuals/Altibase_7.3/kor/iSQL User's Manual.md
ISQL_CONNECTION 지원 프로토콜에 InfiniBand 지원한다는 내용 추가.(7.3매뉴얼은 여기만 고치면 될 것 같긴 합니다만..혹시 몰라서 아래 내용도 수정했습니다)
해당 절에 누락된 환경 변수 프로퍼티 설명 추가
=> iSQL User's Manual - InfiniBand

Manuals/Altibase_7.1/eng/SQL Reference.md, Manuals/Altibase_7.1/kor/SQL Reference.md, Manuals/Altibase_7.3/eng/SQL Reference.md, Manuals/Altibase_7.3/kor/SQL Reference.md, Manuals/Altibase_trunk/eng/SQL Reference.md, Manuals/Altibase_trunk/kor/SQL Reference.md
=> Update SQL Reference

Technical Documents/kor/JavaCompatibility.md, Technical Documents/kor/Supported Platforms.md
- Windows 클라이언트 지원 수정
- AIX 6.1 TL3 삭제
=> BUG-50958 Altibase 7.3 항목 수정

Technical Documents/eng/Supported Platforms.md, Technical Documents/kor/Supported Platforms.md
rhel8.10에서 7.3 호환성 테스트 정보 업데이트
=> BUG-50788 Update Supported Platforms

Manuals/Altibase_7.1/eng/SQL Reference.md, Manuals/Altibase_7.3/eng/SQL Reference.md, Manuals/Altibase_trunk/eng/SQL Reference.md
=> BUG-50766 Comment 321609

Manuals/Tools/Altibase_trunk/eng/Migration Center User's Manual.md, Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
=> BUG-51069 Migration Center User's Manual 이미지 수정

Manuals/Altibase_7.1/eng/API User's Manual.md, Manuals/Altibase_7.1/kor/API User's Manual.md
=> BUG-50982 Update API User's Manual

Manuals/Altibase_7.1/eng/API User's Manual.md
=> Update API User's Manual.md

Manuals/Altibase_7.1/eng/API User's Manual.md
=> Update API User's Manual.md - minor fix

Manuals/Altibase_7.1/eng/Installation Guide.md, Manuals/Altibase_7.1/kor/Installation Guide.md, Manuals/Altibase_7.3/eng/Installation Guide.md, Manuals/Altibase_7.3/kor/Installation Guide.md, Manuals/Altibase_trunk/eng/Installation Guide.md, Manuals/Altibase_trunk/kor/Installation Guide.md, Technical Documents/eng/Supported Platforms.md, Technical Documents/kor/Supported Platforms.md
=> RedHat 9 related updates

Manuals/Altibase_7.1/eng/Installation Guide.md, Manuals/Altibase_7.1/kor/Installation Guide.md
=> fix toc in installation guide

Manuals/Altibase_7.3/eng/Precompiler User's Manual.md, Manuals/Altibase_7.3/kor/Precompiler User's Manual.md, Manuals/Altibase_trunk/eng/Precompiler User's Manual.md, Manuals/Altibase_trunk/kor/Precompiler User's Manual.md
=> BUG-51401 draft updated

Manuals/Altibase_trunk/kor/General_Reference-1.Data Types & Altibase Properties.md
=> BUG-51426 fix

Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
=> BUG-51256 fix

Manuals/Altibase_trunk/kor/CLI User's Manual.md
=> BUG-51369 draft updated

Manuals/Altibase_7.1/kor/API User's Manual.md, Manuals/Altibase_7.3/kor/API User's Manual.md, Manuals/Altibase_trunk/kor/API User's Manual.md
=> BUG-50947 draft updated

Manuals/Altibase_7.3/eng/Adapter for JDBC User's Manual.md, Manuals/Altibase_7.3/eng/Adapter for Oracle User's Manual.md, Manuals/Altibase_trunk/eng/Adapter for JDBC User's Manual.md, Manuals/Altibase_trunk/eng/Adapter for Oracle User's Manual.md
BUG-50744 fixed
기존에 작업하던 PR-479(https://github.com/ALTIBASE/Documents/pull/479) 는 충돌이 있어서, 새로 열었습니다.
소윤님이 7.3에만 작업했던 내용을 7.3, trunk 모두 반영하였습니다.
=> BUG-50744 fixed
